version: '3.4'

services:
  libraryofbooks.webapi:
    image: ${DOCKER_REGISTRY-}libraryofbookswebapi
    build:
      context: .
      dockerfile: src/LibraryOfBooks.WebApi/Dockerfile
    ports:
      - "80"
      - "443"

  libraryofbooks.database:
    image: postgres:latest
    container_name: libraryofbooks.database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=LibraryOfBooksDb
    volumes:
      - ./.containers/libraryofbooks-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"